use section8

CREATE TABLE MANUFACTURERS(
    MANUFACTURER_ID INTEGER PRIMARY KEY NOT NULL,
    MANUFACTURER_NAME VARCHAR(30)
)

CREATE TABLE PRODUCTS_A4(
    PRODUCT_ID INTEGER PRIMARY KEY NOT NULL,
    PRODUCT_DESCRIPTION VARCHAR(600),
    PRODUCT_CATEGORY VARCHAR(10),
    MANUFACTURER_ID INTEGER NOT NULL,
    PRODUCT_LIST_PRICE INTEGER,
    FOREIGN KEY (MANUFACTURER_ID)
    REFERENCES MANUFACTURERS(MANUFACTURER_ID)
)

CREATE TABLE CUSTOMERS_A4(
    CUSTOMER_ID INTEGER PRIMARY KEY NOT NULL,
    CUSTOMER_NAME VARCHAR(20),
    CUSTOMER_EMAIL VARCHAR(30)
)

CREATE TABLE CUSTOMER_TRANSACTIONS_A4(
    TRANSACTION_ID INTEGER PRIMARY KEY NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    TRANSACTION_DATE DATE,
    TRANSACTION_TIME TIME,
    TRANSACTION_TOTAL INTEGER,
    TRANSACTION_TAX INTEGER,
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMERS_A4(CUSTOMER_ID),
)

CREATE TABLE PRODUCT_TRANSACTIONS_A4(
    TRANSACTION_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    PURCHASE_PRICE FLOAT,
    QUANTITY INTEGER,
    TRANSACTION_PRODUCT_TOTAL FLOAT,
    PRIMARY KEY (TRANSACTION_ID,PRODUCT_ID),
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES PRODUCTS_A4(PRODUCT_ID),
    FOREIGN KEY (TRANSACTION_ID)
    REFERENCES CUSTOMER_TRANSACTIONS_A4(TRANSACTION_ID)
)

--SELECT *
--FROM PRODUCT_TRANSACTIONS_A4;

INSERT INTO MANUFACTURERS(MANUFACTURER_ID, MANUFACTURER_NAME) VALUES(101, 'Tesla');
INSERT INTO MANUFACTURERS(MANUFACTURER_ID, MANUFACTURER_NAME) VALUES(102, 'LC_Signs');
INSERT INTO MANUFACTURERS(MANUFACTURER_ID, MANUFACTURER_NAME) VALUES(103, 'Stark Industries');
INSERT INTO MANUFACTURERS(MANUFACTURER_ID, MANUFACTURER_NAME) VALUES(104, 'Morgan Hardware');
INSERT INTO MANUFACTURERS(MANUFACTURER_ID, MANUFACTURER_NAME) VALUES(105, 'Canaropa');

--SELECT * 
--FROM MANUFACTURERS;

INSERT INTO PRODUCTS_A4(PRODUCT_ID, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, MANUFACTURER_ID, PRODUCT_LIST_PRICE) VALUES (201, 'Cyber Truck', 'Vehicles', 101, 80000);
INSERT INTO PRODUCTS_A4(PRODUCT_ID, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, MANUFACTURER_ID, PRODUCT_LIST_PRICE) VALUES (202, 'LED Sign', 'Signage', 102, 100);
INSERT INTO PRODUCTS_A4(PRODUCT_ID, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, MANUFACTURER_ID, PRODUCT_LIST_PRICE) VALUES (203, 'Iron Man Suit', 'Weaponry', 103, 100000);
INSERT INTO PRODUCTS_A4(PRODUCT_ID, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, MANUFACTURER_ID, PRODUCT_LIST_PRICE) VALUES (204, 'Door Handle', 'Hardware', 104, 50);
INSERT INTO PRODUCTS_A4(PRODUCT_ID, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, MANUFACTURER_ID, PRODUCT_LIST_PRICE) VALUES (205, 'Door Viewer', 'Hardware', 105, 15);

--SELECT *
--FROM PRODUCTS_A4;

INSERT INTO CUSTOMERS_A4(CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_EMAIL) VALUES(301, 'Mike Martino', 'Amail@email.com');
INSERT INTO CUSTOMERS_A4(CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_EMAIL) VALUES(302, 'Bike Bartino', 'Bmail@email.com');
INSERT INTO CUSTOMERS_A4(CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_EMAIL) VALUES(303, 'Cike Cartino', 'Cmail@email.com');
INSERT INTO CUSTOMERS_A4(CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_EMAIL) VALUES(304, 'Dike Dartino', 'Dmail@email.com');
INSERT INTO CUSTOMERS_A4(CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_EMAIL) VALUES(305, 'Eike Eartino', 'Email@email.com');

--SELECT *
--FROM CUSTOMERS_A4;

INSERT INTO CUSTOMER_TRANSACTIONS_A4(TRANSACTION_ID, CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_TIME, TRANSACTION_TOTAL, TRANSACTION_TAX) VALUES (401, 301, '2025-03-25', '03:15:47', 81000, 1000);
INSERT INTO CUSTOMER_TRANSACTIONS_A4(TRANSACTION_ID, CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_TIME, TRANSACTION_TOTAL, TRANSACTION_TAX) VALUES (402, 302, '2025-03-26', '04:15:47', 120, 20);
INSERT INTO CUSTOMER_TRANSACTIONS_A4(TRANSACTION_ID, CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_TIME, TRANSACTION_TOTAL, TRANSACTION_TAX) VALUES (403, 303, '2025-03-27', '05:15:47', 110000, 10000);
INSERT INTO CUSTOMER_TRANSACTIONS_A4(TRANSACTION_ID, CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_TIME, TRANSACTION_TOTAL, TRANSACTION_TAX) VALUES (404, 304, '2025-03-28', '09:15:47', 55, 5);
INSERT INTO CUSTOMER_TRANSACTIONS_A4(TRANSACTION_ID, CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_TIME, TRANSACTION_TOTAL, TRANSACTION_TAX) VALUES (405, 305, '2025-03-29', '12:15:47', 17, 2);

--SELECT *
--FROM CUSTOMER_TRANSACTIONS_A4;

INSERT INTO PRODUCT_TRANSACTIONS_A4(TRANSACTION_ID, PRODUCT_ID, PURCHASE_PRICE, QUANTITY, TRANSACTION_PRODUCT_TOTAL) VALUES(401, 201, 80000, 1, 80000);
INSERT INTO PRODUCT_TRANSACTIONS_A4(TRANSACTION_ID, PRODUCT_ID, PURCHASE_PRICE, QUANTITY, TRANSACTION_PRODUCT_TOTAL) VALUES(402, 202, 100, 1, 100);
INSERT INTO PRODUCT_TRANSACTIONS_A4(TRANSACTION_ID, PRODUCT_ID, PURCHASE_PRICE, QUANTITY, TRANSACTION_PRODUCT_TOTAL) VALUES(403, 203, 100000, 1, 100000);
INSERT INTO PRODUCT_TRANSACTIONS_A4(TRANSACTION_ID, PRODUCT_ID, PURCHASE_PRICE, QUANTITY, TRANSACTION_PRODUCT_TOTAL) VALUES(404, 204, 50, 1, 50);
INSERT INTO PRODUCT_TRANSACTIONS_A4(TRANSACTION_ID, PRODUCT_ID, PURCHASE_PRICE, QUANTITY, TRANSACTION_PRODUCT_TOTAL) VALUES(405, 205, 15, 1, 15);

--SELECT *
--FROM PRODUCT_TRANSACTIONS_A4;

ALTER TABLE PRODUCTS_A4
ADD _WEIGHT DECIMAL(9,2) CHECK (_WEIGHT >= 0)

UPDATE PRODUCTS_A4
SET _WEIGHT = 2.5
WHERE PRODUCT_ID = 201;

UPDATE PRODUCTS_A4
SET _WEIGHT = 3.3
WHERE PRODUCT_ID = 202;

UPDATE PRODUCTS_A4
SET _WEIGHT = 4.7
WHERE PRODUCT_ID = 203;

UPDATE PRODUCTS_A4
SET _WEIGHT = 8.8
WHERE PRODUCT_ID = 204;

UPDATE PRODUCTS_A4
SET _WEIGHT = 1.6
WHERE PRODUCT_ID = 205;





ALTER TABLE PRODUCTS_A4
DROP COLUMN _WEIGHT;




DELETE FROM PRODUCTS_A4
WHERE PRODUCT_ID > 10;

DROP TABLE PRODUCT_TRANSACTIONS_A4;

DROP TABLE CUSTOMER_TRANSACTIONS_A4;

DROP TABLE CUSTOMERS_A4;

DROP TABLE PRODUCTS_A4;

DROP TABLE MANUFACTURERS;



